### ISSUE TITLE
Cannot open  the Connection 

### ISSUE THREAD

**Issue by loneharoon** [Ram-N/weatherData#16]
I have installed weatherData package successfully from CRAN. Now, whenever I try to fetch the data I get an error that "cannot open the connection". On checking the data for the specific dates and stations I do find the data on the web page. 

Here is the exact command and the error message thrown
`> getCurrentTemperature("PIT")
URL does not seem to exist: http://www.wunderground.com/history/airport/PIT/2016/3/4/DailyHistory.html?format=1
The original error message:
cannot open the connectionNULL
Warning message:
In getDetailedWeather(station_id, Sys.Date(), opt_warnings = TRUE) :
  Unable to get data from URL
 Check if URL is reachable`

What might be the possible reason for these errors?

**Comment by LaurentBerder** [comment]
I receive the same errors.
Whatever the station_id I use, it returns:
`In getDetailedWeather(station_id, Sys.Date(), opt_warnings = TRUE) :
  Unable to get data from URL
 Check if URL is reachable`
The URL provided works in a browser, but R can't seem to pick it up.

**Comment by alexander-raboin** [comment]
you all get this resolved? I am having the same issue
Retrieving from: http://www.wunderground.com/history/airport/KATL/2015/1/1/CustomHistory.html?dayend=31&monthend=12&yearend=2015&req_city=NA&req_state=NA&req_statename=NA&format=1
URL does not seem to exist: http://www.wunderground.com/history/airport/KATL/2015/1/1/CustomHistory.html?dayend=31&monthend=12&yearend=2015&req_city=NA&req_state=NA&req_statename=NA&format=1
The original error message:
cannot open the connectionChecking Summarized Data Availability For KATL
Found 0 records for 2015-01-01 to 2015-12-31
Data is Not Available
Warning message:
In isObtainedDataValid(wxdata, station_id, custom_url) :
  There seems to be no data in the URL.
Try going to the URL via your browser and seeing there is data.
                    
 Inspect the validity of the URL being tried:
 http://www.wunderground.com/history/airport/KATL/2015/1/1/CustomHistory.html?dayend=31&monthend=12&yearend=2015&req_city=NA&req_state=NA&req_statename=NA&format=1

**Comment by LaurentBerder** [comment]
@alexander-raboin that's rather surprising, since there is data when I click on your link

**Comment by andypicke** [comment]
I don't know if this is related, but I was making a shiny app that reads data from weather underground, and got similar error message. I was using readr::read_csv , and getting an error message that 'curl' was not available and it was resorting back to 'url'. I loaded the 'curl' library, and that seemed to fix the problem.
