### ISSUE TITLE
Failing to fetch URL even though URL is valid

### ISSUE THREAD

**Issue by cauldnz** [Ram-N/weatherData#17]
I'm struggling to get this package to work correctly.
`getStationCode("Buffalo", region="WY")`
Works correctly.

`checkDataAvailability("KBYG", "2011-01-02")`
Does not work and nor do any of the getWeather functions.
Returns: URL does not seem to exist: http://www.wunderground.com/history/airport/KBYG/2011/1/2/DailyHistory.html?format=1

I can grab that URL and open it just fine in a browser on the same machine.

`> version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree   
`

On Ubuntu 14.04

Anyone have any thoughts or pointers before I go and teach myself how to debug packages :-)

**Comment by cauldnz** [comment]
Looks to be an issue with the base url package calling Weather Underground. I suspect that they are looking for a valid host header. I replaced the base url function with the curl package and have submitted a pull request.

**Comment by Ram-N** [comment]
Thanks, Chris. A few others are also experiencing the problem, but it is not happening consistently, it seems.
As for you pull request, the Travis Build is failing, so I need to look into it more. (@ozagordi also seems to have looked into it, but the Build is not passing.)

**Comment by ozagordi** [comment]
Right. Sorry for the confusion with many pull requests close to each other, I though it was a small thing. I'm developing locally and if my tests work I'll try again.

**Comment by israeldi** [comment]
I would like to add to the discussion. The weatherData package has been invaluable for a class project in one of my Stats classes. The main function I run is getWeatherForDate, but I get the error in the screenshot. I am running this on Rstudio on my Mac. 
![screen shot 2016-03-31 at 4 39 15 pm](https://cloud.githubusercontent.com/assets/15841691/14190169/57a66a86-f75f-11e5-9c62-828b24221d19.png)

**Comment by loneharoon** [comment]
I am facing the same issue. Even though the data are available for the date while checking on browser, but this package shows Station data not available

**Comment by ozagordi** [comment]
I filed a new pull request #21. I don't think I solved the issue _in toto_, but it seems an improvement to me. Some functionalities are still giving troubles when tested on Travis, I would like to hear from others.

**Comment by loneharoon** [comment]
I can see the changes you have made. But, it seems that changes are not reflected in the main github `weatherData` library. How can I get the updated `weatherData` library? Is there a specific branch which I can download?

**Comment by loneharoon** [comment]
Thanks ozagordi. I tried your [updated repository](https://github.com/ozagordi/weatherData). It is working fine.

**Comment by Ram-N** [comment]
Great. Thanks, ozagordi. If Israeldi and/or chris auld nz can confirm that Ozagordi's fix works for them too, I will merge his latest pull request. I really appreciate all of your help. Ram

**Comment by khitengoku** [comment]
How do I use the updated repository?  I am sorry for my ignorance.  I'm new to R.  I downgraded to 3.1.3 so I could use devtools.  Unfortunately, the weatherData file still doesn't work for me.  I think I need to try the fix from ozagordi.

**Comment by loneharoon** [comment]
@khitengoku. I can understand your issue and the frustration it results in. I don't know when will Ram-N update this repository, but for temporary basis, you can use [this](https://github.com/ozagordi/weatherData) repository from Ozagordi. It worked for me perfectly.

**Comment by khitengoku** [comment]
Thank you.  But how do I use it?  In place of the Ram version?   I'm a noob.

**Comment by loneharoon** [comment]
These steps should work. 
`remove.packages(weatherData) #this will remove installed version
library("devtools")
install_github("ozagordi/weatherData")# will install new version`

If you face any problem, let me know at haroonr@iiitd.ac.in

**Comment by khitengoku** [comment]
You're the governor.  Thanks.

**Comment by Ram-N** [comment]
Khitengoku,

If you can confirm that you are no longer facing the issue with Ozagordi's repo, I will merge it. I am looking for confirmation. Thanks much, Ram

**Comment by khitengoku** [comment]
I still have some issue with certain pulls.   But it seems to work for the American weather stations.   Foreign weather stations don't all seem to work, unless I don't k ow what I'm doing.   But airport stations do.

**Comment by CandyBoat** [comment]
@Ram-N Hi Ram, I tried the new version fetching data for city Minneapolis, Minnesota from 04/01/2015 to 09/30/2015, it worked perfectly! Thanks for your work!

**Comment by gadenbuie** [comment]
I can also confirm having experienced the same problem, which was solved using the `ozagordi/weatherData` fork.

With `devtools::install_github('ram-n/weatherData')`:

```r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] weatherData_0.4.4

loaded via a namespace (and not attached):
[1] plyr_1.8.3  Rcpp_0.12.4

> weather.ktpa <- getWeatherForDate('KTPA', start_date = '2016-04-01', end_date = Sys.Date())
URL to Try:
 http://www.wunderground.com/history/airport/KTPA/2016/4/1/CustomHistory.html?dayend=19&monthend=4&yearend=2016&req_city=NA&req_state=NA&req_statename=NA&format=1

Retrieving from: http://www.wunderground.com/history/airport/KTPA/2016/4/1/CustomHistory.html?dayend=19&monthend=4&yearend=2016&req_city=NA&req_state=NA&req_statename=NA&format=1
URL does not seem to exist: http://www.wunderground.com/history/airport/KTPA/2016/4/1/CustomHistory.html?dayend=19&monthend=4&yearend=2016&req_city=NA&req_state=NA&req_statename=NA&format=1
The original error message:
cannot open the connectionChecking Summarized Data Availability For KTPA
Found 0 records for 2016-04-01 to 2016-04-19
Data is Not Available
Warning message:
In isObtainedDataValid(wxdata, station_id, custom_url) :
  There seems to be no data in the URL.
Try going to the URL via your browser and seeing if there is data.

 Inspect the validity of the URL being tried:
 http://www.wunderground.com/history/airport/KTPA/2016/4/1/CustomHistory.html?dayend=19&monthend=4&yearend=2016&req_city=NA&req_state=NA&req_statename=NA&format=1
```

With `devtools::install_github('ozagordi/weatherData')`:

```r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] weatherData_0.4.5

loaded via a namespace (and not attached):
 [1] httr_1.1.0      plyr_1.8.3      R6_2.1.2        tools_3.2.3
 [5] withr_1.0.0     curl_0.9.7      Rcpp_0.12.4     memoise_1.0.0
 [9] git2r_0.13.1    digest_0.6.9    devtools_1.10.0

> weather.ktpa <- getWeatherForDate('KTPA', start_date = '2016-04-01', end_date = Sys.Date())
URL to Try:
 https://www.wunderground.com/history/airport/KTPA/2016/4/1/CustomHistory.html?dayend=19&monthend=4&yearend=2016&req_city=NA&req_state=NA&req_statename=NA&format=1

Retrieving from: https://www.wunderground.com/history/airport/KTPA/2016/4/1/CustomHistory.html?dayend=19&monthend=4&yearend=2016&req_city=NA&req_state=NA&req_statename=NA&format=1
[1] 20
The following columns are available:
 [1] "EDT"                       "Max_TemperatureF"
 [3] "Mean_TemperatureF"         "Min_TemperatureF"
 ...
```

**Comment by Ram-N** [comment]
Thanks, Gadenbieu and Haroon for confirming. And to Ozagordi for the fixes. I have merged pull request.

**Comment by Ram-N** [comment]
This fix is now on CRAN, as weatherData version 0.5.0.
Thanks all.

**Comment by abhaya2sahoo** [comment]
Hello,
I am struggling to get the result on the sample code: checkDataAvailability("KBYG", "2011-01-02") for this packages.

I have tried with various r version. But not able to fix the issues.
I am getting the error messages: 

 checkDataAvailability("KBYG", "2011-01-02")
Getting data from:
 https://www.wunderground.com/history/airport/KBYG/2011/1/2/DailyHistory.html?format=1

URL does not seem to exist: https://www.wunderground.com/history/airport/KBYG/2011/1/2/DailyHistory.html?format=1
The original error message:
HTTP error 400.Checking Data Availability For KBYG
Data is Not Available
[1] 0
Warning message:
In getDetailedWeather(station_id, check_date, station_type, opt_temperature_columns = T,  :
  Unable to get data from URL
 Check if URL is reachable

======================

Kindly help me to fix this issue...

**Comment by abhaya2sahoo** [comment]
Hello Ram-N,
I have tried to reinstall the weatherData version 0.5.0 package from: 
https://cran.r-project.org/src/contrib/Archive/weatherData/

When i checked with help(weatherData) code, i got the below message:
===================
Error in fetch(key) : 
  lazy-load database 'C:/Program Files/R/R-3.5.0/library/weatherData/help/weatherData.rdb' is corrupt
====================

Kindly suggest how to debug. 

Thanking you all in advance....

**Comment by Ram-N** [comment]
Hello Abaya:

This package doesn't work anymore because weatherUnderground has blocked
its access. I am afraid that you'll have to find other packages to get the
weather data.
