### ISSUE TITLE
Update CRAN

### ISSUE THREAD

**Issue by ambodi** [Ram-N/weatherData#22]
Installing from Github works but CRAN package is still broken after https://github.com/Ram-N/weatherData/issues/17 is fixed. Can you do it because ShinyApps are failing too and you cant install from github there.

**Comment by Ram-N** [comment]
@ambodi (Amir),

You should be able to use any Github packages in ShinyApps. Make sure that your devtools is current.
See below, from ShinyApps help pages:

**Package sources**
Currently the shinyapps.io service supports deploying packages installed from CRAN, GitHub, and BioConductor. We will look to add support for R-Forge packages in the future.

Important note on GitHub packages

Only packages installed from GitHub with devtools::install_github in version 1.4 (or later) of devtools are supported. Packages installed with an earlier version of devtools must be reinstalled before you can deploy your application. If you get an error such as “PackageSourceError” when you attempt to deploy, check that you have installed any package from Github with devtools 1.4 or later.

**Comment by archenemies** [comment]
I also tried installing the CRAN package first and found it not working. Is that like a rite of passage that every user has to go through? It would be nice if you could even just put a warning on the CRAN package saying "use the GitHub version instead"...

**Comment by Ram-N** [comment]
All, thanks for your patience. It takes a long time to work on all the fixes and to get a package ready for CRAN. (I'd really like to be able to put up a warning on CRAN, but even that update is not trivial.)

Good news is that now this is up on CRAN. version 0.5.0.

Thanks again for your patience.
