### ISSUE TITLE
Error in names(wx_df) <- header_names :    'names' attribute [23] must be the same length as the vector [20]

### ISSUE THREAD

**Issue by dggoldst** [Ram-N/weatherData#38]
Executing the first four lines will reproduce the error
`
> YEAR = 2013 
> startdate = paste(YEAR, "-01-01", sep = "") 
> enddate = paste(YEAR, "-12-31", sep = "") 
> checkSummarizedDataAvailability("PAVW", startdate, enddate) 
URL to Try:  https://www.wunderground.com/history/airport/PAVW/2013/1/1/CustomHistory.html?dayend=31&monthend=12&yearend=2013&req_city=NA&req_state=NA&req_statename=NA&format=1  Retrieving from: https://www.wunderground.com/history/airport/PAVW/2013/1/1/CustomHistory.html?dayend=31&monthend=12&yearend=2013&req_city=NA&req_state=NA&req_statename=NA&format=1 [1] 364 The following columns are available:  [1] "AKST"                      "Max_TemperatureF"          "Mean_TemperatureF"         "Min_TemperatureF"           [5] "Max_Dew_PointF"            "MeanDew_PointF"            "Min_DewpointF"             "Max_Humidity"               [9] "Mean_Humidity"             "Min_Humidity"              "Max_Sea_Level_PressureIn"  "Mean_Sea_Level_PressureIn" [13] "Min_Sea_Level_PressureIn"  "Max_VisibilityMiles"       "Mean_VisibilityMiles"      "Min_VisibilityMiles"       [17] "Max_Wind_SpeedMPH"         "Mean_Wind_SpeedMPH"        "Max_Gust_SpeedMPH"         "PrecipitationIn"           [21] "CloudCover"                "Events"                    "WindDirDegrees"            
Error in names(wx_df) <- header_names :    'names' attribute [23] must be the same length as the vector [20]
`

**Comment by Ram-N** [comment]
Thank you, @dggoldst. Yes, I am getting the same error. Let me troubleshoot it and upload the fix to github. I will notify you.
Thanks again for reporting it.

**Comment by Ram-N** [comment]
@dggoldst I found the source of this error and have fixed it. Could you please download the latest version of the pakage (from github *NOT* CRAN) and verify that it works for you? Thanks.

To install the latest version in github:
```
install.packages("devtools")
library("devtools")
install_github("Ram-N/weatherData")
```

**Comment by dggoldst** [comment]
I tried it and it works. Not only does it not throw an error, it actually can fetch the data for that airport.

**Comment by roquealex** [comment]
Hello Ram,

This bug fix is breaking the PWS I'm trying to read. Give aa try to this command:

> test <- getDetailedWeather("IYUCATNT2", "2017-01-01",station_type='id',opt_all_columns=T)
> head(test)

You will see that the column names except for time use the default values. The problem is that the data comes with an extra "," at the end compared to the column names. I forked this and added back the lines that remove the comas for now since this seem to work for that PWS I'm working with.

Thanks
