### ISSUE TITLE
Bad URL link

### ISSUE THREAD

**Issue by chemiery** [Ram-N/weatherData#43]
Getting an error message when submitting this command: 

checkDataAvailabilityForDateRange("SFO", "2010-10-29", "2013-01-12")

The error message is: 

Getting data from:
 https://www.wunderground.com/history/airport/SFO/2010/10/29/DailyHistory.html?format=1

URL does not seem to exist: https://www.wunderground.com/history/airport/SFO/2010/10/29/DailyHistory.html?format=1
The original error message:
HTTP error 400.Getting data from:
 https://www.wunderground.com/history/airport/SFO/2013/1/12/DailyHistory.html?format=1

URL does not seem to exist: https://www.wunderground.com/history/airport/SFO/2013/1/12/DailyHistory.html?format=1
The original error message:
HTTP error 400.Checking Data Availability For SFO
Found 0 records for 2010-10-29
Found 0 records for 2013-01-12
Data is Not Available

[1] 0
Warning messages:
1: In getDetailedWeather(station_id, start_date, station_type, opt_temperature_columns = T,  :
  Unable to get data from URL
 Check if URL is reachable
2: In getDetailedWeather(station_id, end_date, station_type, opt_temperature_columns = T,  :
  Unable to get data from URL
 Check if URL is reachable

**Comment by svergeylen** [comment]
Trying to use the same package. Getting the same error. Is this package still maintained ? Can we change the URL easily ?

**Comment by Ram-N** [comment]
Folks: The website (WeatherUnderground) stopped this package from accessing their site. So I have removed this package from CRAN. (It is no longer usable.) Sorry about that.
